// <auto-generated />
using Bookshelf.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Bookshelf.Api.Migrations
{
    [DbContext(typeof(BookshelfContext))]
    [Migration("20180506090711_Trunk")]
    partial class Trunk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Bookshelf.Author", b =>
                {
                    b.Property<Guid>("IdAuthor")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<int>("Gid");

                    b.Property<Guid>("IdObject");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<short>("Permission");

                    b.Property<int>("Uid");

                    b.HasKey("IdAuthor");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Bookshelf.AuthorBook", b =>
                {
                    b.Property<Guid>("IdAuthor");

                    b.Property<Guid>("IdBook");

                    b.Property<Guid?>("BookId");

                    b.HasKey("IdAuthor", "IdBook");

                    b.HasIndex("BookId");

                    b.ToTable("AuthorBook");
                });

            modelBuilder.Entity("Bookshelf.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ddcn");

                    b.Property<int>("Gid");

                    b.Property<Guid>("IdObject");

                    b.Property<string>("Isbn10");

                    b.Property<string>("Isbn13");

                    b.Property<short>("Pages");

                    b.Property<short>("Permission");

                    b.Property<Guid>("PublisherId");

                    b.Property<string>("Subtitle");

                    b.Property<string>("Title");

                    b.Property<int>("Uid");

                    b.HasKey("BookId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Bookshelf.Publisher", b =>
                {
                    b.Property<Guid>("PublisherId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("PublisherId");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Bookshelf.AuthorBook", b =>
                {
                    b.HasOne("Bookshelf.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId");

                    b.HasOne("Bookshelf.Author", "Author")
                        .WithMany()
                        .HasForeignKey("IdAuthor")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bookshelf.Book", b =>
                {
                    b.HasOne("Bookshelf.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
